# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='count',
        ),
        migrations.AlterField(
            model_name='urls',
            name='id',
            field=models.SlugField(default='R6MyyNRa', primary_key=True, serialize=False),
        ),
    ]
