# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-30 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170830_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='id',
            field=models.SlugField(default='fqJE7KQC', primary_key=True, serialize=False),
        ),
    ]
