# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='httpurl',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='urls',
            name='short_id',
        ),
        migrations.AddField(
            model_name='urls',
            name='id',
            field=models.SlugField(default='XVPkuXmR', primary_key=True, serialize=False),
        ),
    ]
